name: Test on Windows

on:
  workflow_dispatch:
  workflow_call:

jobs:
  windows:
    name: Test Windows
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          path: angr-managmenet
      - uses: actions/checkout@v4
        with:
          repository: angr/binaries
          path: binaries
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - run: python -m venv $HOME/venv
        name: Create venv
        shell: bash
      - run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          call %USERPROFILE%\venv\Scripts\activate
          pip install "setuptools>=59" wheel cffi "unicorn==2.0.1.post1"
          pip install git+https://github.com/angr/archinfo.git
          pip install git+https://github.com/angr/pyvex.git
          pip install git+https://github.com/angr/cle.git
          pip install git+https://github.com/angr/claripy.git
          pip install git+https://github.com/angr/ailment.git
          pip install --no-build-isolation git+https://github.com/angr/angr.git
        name: Install dependencies
        shell: cmd
      - run: |
          call %USERPROFILE%\venv\Scripts\activate
          pip install ./angr-management[testing]
        name: Install angr
        shell: cmd
      - run: |
          call %USERPROFILE%\venv\Scripts\activate
          pytest -n auto angr-management
        name: Run pytest
        shell: cmd
